// Comprehensive mock data matching API response shapes

// User/Auth Mock Data
export const mockCurrentUser = {
  id: "user_001",
  email: "john.doe@example.com",
  full_name: "John Doe",
  profile_pic_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=john",
  theme_hue: 250,
  created_at: "2024-01-15T10:30:00Z",
  updated_at: "2024-12-20T15:45:00Z",
  status: "active",
};

export const mockUsers = [
  {
    id: "user_001",
    email: "john.doe@example.com",
    full_name: "John Doe",
    profile_pic_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=john",
    status: "active",
  },
  {
    id: "user_002",
    email: "jane.smith@example.com",
    full_name: "Jane Smith",
    profile_pic_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane",
    status: "active",
  },
  {
    id: "user_003",
    email: "mike.wilson@example.com",
    full_name: "Mike Wilson",
    profile_pic_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=mike",
    status: "active",
  },
  {
    id: "user_004",
    email: "sarah.johnson@example.com",
    full_name: "Sarah Johnson",
    profile_pic_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    status: "active",
  },
  {
    id: "user_005",
    email: "alex.brown@example.com",
    full_name: "Alex Brown",
    profile_pic_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
    status: "active",
  },
];

// Groups Mock Data
export const mockGroups = [
  {
    id: "group_001",
    name: "Family Planning",
    description: "Plan family events, vacations, and gatherings",
    owner: "john.doe@example.com",
    type: "family",
    created_at: "2024-01-20T08:00:00Z",
    updated_at: "2024-12-20T10:00:00Z",
    members: ["john.doe@example.com", "jane.smith@example.com", "mike.wilson@example.com", "sarah.johnson@example.com"],
    member_names: {
      "john.doe@example.com": "John Doe",
      "jane.smith@example.com": "Jane Smith",
      "mike.wilson@example.com": "Mike Wilson",
      "sarah.johnson@example.com": "Sarah Johnson",
    },
  },
  {
    id: "group_002",
    name: "Work Colleagues",
    description: "Coordinate team projects and meetings",
    owner: "jane.smith@example.com",
    type: "work",
    created_at: "2024-02-10T09:30:00Z",
    updated_at: "2024-12-19T14:20:00Z",
    members: ["john.doe@example.com", "jane.smith@example.com", "mike.wilson@example.com", "alex.brown@example.com"],
    member_names: {
      "john.doe@example.com": "John Doe",
      "jane.smith@example.com": "Jane Smith",
      "mike.wilson@example.com": "Mike Wilson",
      "alex.brown@example.com": "Alex Brown",
    },
  },
  {
    id: "group_003",
    name: "Book Club",
    description: "Monthly book discussions and reviews",
    owner: "mike.wilson@example.com",
    type: "hobby",
    created_at: "2024-03-05T07:15:00Z",
    updated_at: "2024-12-18T16:30:00Z",
    members: ["john.doe@example.com", "mike.wilson@example.com", "sarah.johnson@example.com"],
    member_names: {
      "john.doe@example.com": "John Doe",
      "mike.wilson@example.com": "Mike Wilson",
      "sarah.johnson@example.com": "Sarah Johnson",
    },
  },
];

// Invitations Mock Data
export const mockInvitations = [
  {
    id: "invite_001",
    group_id: "group_001",
    inviter_email: "jane.smith@example.com",
    inviter_name: "Jane Smith",
    invitee_email: "john.doe@example.com",
    group_name: "Family Planning",
    status: "pending",
    created_date: "2024-12-19T10:00:00Z",
  },
  {
    id: "invite_002",
    group_id: "group_003",
    inviter_email: "sarah.johnson@example.com",
    inviter_name: "Sarah Johnson",
    invitee_email: "john.doe@example.com",
    group_name: "Book Club",
    status: "pending",
    created_date: "2024-12-18T14:30:00Z",
  },
];

// Messages/Chat Mock Data
export const mockMessages = [
  {
    id: "msg_001",
    group_id: "group_001",
    sender_email: "john.doe@example.com",
    sender_name: "John Doe",
    content: "Hey everyone! Should we plan a summer vacation?",
    created_date: "2024-12-20T09:00:00Z",
    updated_date: "2024-12-20T09:00:00Z",
    type: "text",
    attachments: [],
    reactions: { "👍": ["jane.smith@example.com", "mike.wilson@example.com"] },
    read_by: ["jane.smith@example.com", "mike.wilson@example.com", "sarah.johnson@example.com"],
  },
  {
    id: "msg_002",
    group_id: "group_001",
    sender_email: "jane.smith@example.com",
    sender_name: "Jane Smith",
    content: "Great idea! I'm thinking beach or mountains?",
    created_date: "2024-12-20T09:15:00Z",
    updated_date: "2024-12-20T09:15:00Z",
    type: "text",
    attachments: [],
    reactions: { "❤️": ["john.doe@example.com", "sarah.johnson@example.com"] },
    read_by: ["john.doe@example.com", "mike.wilson@example.com", "sarah.johnson@example.com"],
  },
  {
    id: "msg_003",
    group_id: "group_001",
    sender_email: "mike.wilson@example.com",
    sender_name: "Mike Wilson",
    content: "Mountains for me! The hiking trails are amazing.",
    created_date: "2024-12-20T09:30:00Z",
    updated_date: "2024-12-20T09:30:00Z",
    type: "text",
    attachments: [],
    reactions: { "🏔️": ["john.doe@example.com"] },
    read_by: ["john.doe@example.com", "jane.smith@example.com", "sarah.johnson@example.com"],
  },
  {
    id: "msg_004",
    group_id: "group_002",
    sender_email: "alex.brown@example.com",
    sender_name: "Alex Brown",
    content: "Project deadline moved to next Friday",
    created_date: "2024-12-20T10:00:00Z",
    updated_date: "2024-12-20T10:00:00Z",
    type: "text",
    attachments: [],
    reactions: {},
    read_by: ["jane.smith@example.com", "mike.wilson@example.com"],
  },
];

// Calendar Events Mock Data
export const mockCalendarEvents = [
  {
    id: "event_001",
    group_id: "group_001",
    title: "Family Dinner",
    description: "Weekly family gathering at home",
    date: "2024-12-22T18:00:00Z",
    start_time: "18:00",
    end_time: "20:00",
    location: "123 Family Lane, Hometown",
    organizer_email: "john.doe@example.com",
    organizer_name: "John Doe",
    attendees: ["john.doe@example.com", "jane.smith@example.com", "mike.wilson@example.com", "sarah.johnson@example.com"],
    status: "confirmed",
    created_date: "2024-12-15T10:00:00Z",
  },
  {
    id: "event_002",
    group_id: "group_002",
    title: "Team Standup",
    description: "Daily team sync-up meeting",
    date: "2024-12-21T10:00:00Z",
    start_time: "10:00",
    end_time: "10:30",
    location: "Conference Room A",
    organizer_email: "jane.smith@example.com",
    organizer_name: "Jane Smith",
    attendees: ["john.doe@example.com", "jane.smith@example.com", "mike.wilson@example.com", "alex.brown@example.com"],
    status: "confirmed",
    created_date: "2024-12-10T08:00:00Z",
  },
  {
    id: "event_003",
    group_id: "group_001",
    title: "Vacation Planning Meeting",
    description: "Discuss summer vacation options and dates",
    date: "2024-12-23T19:00:00Z",
    start_time: "19:00",
    end_time: "20:00",
    location: "Video Call",
    organizer_email: "john.doe@example.com",
    organizer_name: "John Doe",
    attendees: ["john.doe@example.com", "jane.smith@example.com", "mike.wilson@example.com", "sarah.johnson@example.com"],
    status: "confirmed",
    created_date: "2024-12-18T09:00:00Z",
  },
  {
    id: "event_004",
    group_id: "group_003",
    title: "January Book Club Meeting",
    description: "Discuss 'The Midnight Library'",
    date: "2025-01-15T18:30:00Z",
    start_time: "18:30",
    end_time: "20:00",
    location: "Coffee House Downtown",
    organizer_email: "mike.wilson@example.com",
    organizer_name: "Mike Wilson",
    attendees: ["john.doe@example.com", "mike.wilson@example.com", "sarah.johnson@example.com"],
    status: "confirmed",
    created_date: "2024-12-01T11:00:00Z",
  },
];

// Tasks Mock Data
export const mockTasks = [
  {
    id: "task_001",
    group_id: "group_001",
    title: "Research vacation destinations",
    description: "Look up beach and mountain resorts",
    assigned_to: ["john.doe@example.com"],
    assigned_by: "john.doe@example.com",
    status: "doing",
    label: "important",
    due_date: "2024-12-25",
    created_date: "2024-12-15T10:00:00Z",
    updated_date: "2024-12-20T14:30:00Z",
    tags: ["vacation", "planning"],
    completed: false,
    parent_task_id: null,
  },
  {
    id: "task_002",
    group_id: "group_001",
    title: "Prepare family budget",
    description: "Create a budget for vacation expenses",
    assigned_to: ["jane.smith@example.com"],
    assigned_by: "john.doe@example.com",
    status: "todo",
    label: "important",
    due_date: "2024-12-24",
    created_date: "2024-12-18T09:00:00Z",
    updated_date: "2024-12-20T11:00:00Z",
    tags: ["vacation", "finance"],
    completed: false,
    parent_task_id: null,
  },
  {
    id: "task_003",
    group_id: "group_002",
    title: "Complete project documentation",
    description: "Write comprehensive API documentation",
    assigned_to: ["mike.wilson@example.com"],
    assigned_by: "jane.smith@example.com",
    status: "doing",
    label: "normal",
    due_date: "2024-12-27",
    created_date: "2024-12-10T08:00:00Z",
    updated_date: "2024-12-20T13:00:00Z",
    tags: ["documentation", "project"],
    completed: false,
    parent_task_id: null,
  },
  {
    id: "task_004",
    group_id: "group_002",
    title: "Code review",
    description: "Review PR #234",
    assigned_to: ["alex.brown@example.com"],
    assigned_by: "mike.wilson@example.com",
    status: "todo",
    label: "important",
    due_date: "2024-12-21",
    created_date: "2024-12-19T14:00:00Z",
    updated_date: "2024-12-20T10:00:00Z",
    tags: ["code-review", "project"],
    completed: false,
    parent_task_id: null,
  },
  {
    id: "task_005",
    group_id: "group_003",
    title: "Finish reading current book",
    description: "Complete 'The Midnight Library' before meeting",
    assigned_to: ["john.doe@example.com"],
    assigned_by: "john.doe@example.com",
    status: "doing",
    label: "normal",
    due_date: "2025-01-14",
    created_date: "2024-12-01T10:00:00Z",
    updated_date: "2024-12-20T09:00:00Z",
    tags: ["book-club", "reading"],
    completed: false,
    parent_task_id: null,
  },
];

// Notes Mock Data
export const mockNotes = [
  {
    id: "note_001",
    group_id: "group_001",
    title: "Vacation Ideas",
    content: "# Vacation Ideas\n\n## Beach Options\n- Hawaii\n- Caribbean\n- Mexico\n\n## Mountain Options\n- Colorado\n- Swiss Alps\n- Japanese Alps",
    author_email: "john.doe@example.com",
    author_name: "John Doe",
    created_date: "2024-12-15T10:00:00Z",
    updated_date: "2024-12-20T14:30:00Z",
    tags: ["vacation", "planning"],
    is_pinned: true,
    color: "#ffffff",
    last_edited_by: "john.doe@example.com",
    last_edited_name: "John Doe",
  },
  {
    id: "note_002",
    group_id: "group_001",
    title: "Budget Estimates",
    content: "Estimated costs for each destination...",
    author_email: "jane.smith@example.com",
    author_name: "Jane Smith",
    created_date: "2024-12-18T09:00:00Z",
    updated_date: "2024-12-19T15:30:00Z",
    tags: ["vacation", "finance"],
    is_pinned: false,
    color: "#ffffff",
    last_edited_by: "jane.smith@example.com",
    last_edited_name: "Jane Smith",
  },
  {
    id: "note_003",
    group_id: "group_002",
    title: "Project Architecture",
    content: "# System Design\n\n## Components\n- Frontend: React\n- Backend: Node.js\n- Database: PostgreSQL",
    author_email: "mike.wilson@example.com",
    author_name: "Mike Wilson",
    created_date: "2024-12-10T08:00:00Z",
    updated_date: "2024-12-20T11:00:00Z",
    tags: ["project", "architecture"],
    is_pinned: true,
    color: "#ffffff",
    last_edited_by: "mike.wilson@example.com",
    last_edited_name: "Mike Wilson",
  },
  {
    id: "note_004",
    group_id: "group_003",
    title: "Book Review Notes",
    content: "Key themes and characters...",
    author_email: "john.doe@example.com",
    author_name: "John Doe",
    created_date: "2024-12-01T10:00:00Z",
    updated_date: "2024-12-18T13:00:00Z",
    tags: ["book-club", "review"],
    is_pinned: false,
    color: "#ffffff",
    last_edited_by: "john.doe@example.com",
    last_edited_name: "John Doe",
  },
];

// Settings Mock Data
export const mockSettings = {
  notifications: {
    email_on_event: true,
    email_on_task: true,
    email_on_message: false,
    push_enabled: true,
  },
  privacy: {
    profile_visible: true,
    show_online_status: true,
    allow_group_invites: true,
  },
};

// TaskLists (for Tasks page)
export const mockTaskLists = [
  {
    id: "list_001",
    group_id: "group_001",
    name: "Vacation Planning",
    order: 0,
  },
  {
    id: "list_002",
    group_id: "group_002",
    name: "Development Tasks",
    order: 0,
  },
];

// TypingStatus (for real-time typing indicators)
export const mockTypingStatuses = [] as any[];

// Presence (for real-time presence tracking)
export const mockPresences = [] as any[];
