export interface Note {
  id?: string; // Sometimes mapped by plugins
  _id?: string; // Raw MongoDB ID
  
  // Core Info
  title: string;
  content: string; // HTML string from the rich text editor
  group_id: string;
  
  // Author Info
  author_email: string;
  author_name: string;
  
  // Edit History
  last_edited_by?: string;
  last_edited_name?: string;
  
  // Preferences
  is_pinned: boolean;
  color: string; // Hex color code (e.g., '#FCE7F3', '#ffffff')
  
  // Timestamps (usually auto-generated by MongoDB)
  created_at?: string;
  updated_at?: string;
}

/**
 * Payload for POST /v1/notes
 */
export interface CreateNotePayload {
  title: string;
  content?: string;
  group_id: string;
  is_pinned?: boolean;
  color?: string;
}

/**
 * Payload for PATCH /v1/notes/:id
 */
export interface UpdateNotePayload {
  title?: string;
  content?: string;
  is_pinned?: boolean;
  color?: string;
}